include_search_path:
 /Users/zhangchao/code/b57.6_opt/Code_LTE/rnlc/infra/include
 /Users/zhangchao/code/b57.6_opt/Code_LTE/rnlc/dcm/ng/include
 /Users/zhangchao/code/b57.6_opt/Code_CPUPlatform/pub/h/umf
 /Users/zhangchao/code/b57.6_opt/Code_CPUPlatform/platapi/brs
 /Users/zhangchao/code/b57.6_opt/Code_CPUPlatform/platapi/scs
 /Users/zhangchao/code/b57.6_opt/Code_CPUPlatform/platapi/pub
 /Users/zhangchao/code/b57.6_opt/Code_CPUPlatform/platapi/oam
 /Users/zhangchao/code/b57.6_opt/Code_CPUPlatform/platapi/oss
 /Users/zhangchao/code/b57.6_opt/Code_CPUPlatform/platapi/dbs
 /Users/zhangchao/code/b57.6_opt/Code_CPUPlatform/platapi/bsp
 /Users/zhangchao/code/b57.6_opt/Code_CPUPlatform/platapi/brs
 /Users/zhangchao/code/b57.6_opt/Code_LTE/pub/include
 /Users/zhangchao/code/b57.6_opt/Code_LTE/oss/pub/include
 /Users/zhangchao/code/b57.6_opt/Code_LTE/oss/topo/include
 /Users/zhangchao/code/b57.6_opt/Code_LTE/dbs/access/include
 /Users/zhangchao/code/b57.6_opt/Code_LTE/dbs/agent/include
 /Users/zhangchao/code/b57.6_opt/Code_LTE/dbs/common/include
 /Users/zhangchao/code/b57.6_opt/Code_LTE/dbs/pub/include
 /Users/zhangchao/code/b57.6_opt/Code_LTE/dbs/table/include
 /Users/zhangchao/code/b57.6_opt/Code_LTE/dbs/trigger/include
 /Users/zhangchao/code/b57.6_opt/Code_LTE/oam/pub/include
 /Users/zhangchao/code/b57.6_opt/Code_LTE/rrm/pub/include
 /Users/zhangchao/code/b57.6_opt/Code_LTE/rnlc/pub/include
 /Users/zhangchao/code/b57.6_opt/Code_LTE/rnlc/common/include
 /Users/zhangchao/code/b57.6_opt/Code_LTE/rnlc/dcm/relay/include
 /Users/zhangchao/code/b57.6_opt/Code_USF/ccl/pub/include
 /Users/zhangchao/code/b57.6_opt/Code_USF/ccl/adapter/include
 /Users/zhangchao/code/b57.6_opt/Code_USF/ccl/algorithm/include
 /Users/zhangchao/code/b57.6_opt/Code_USF/ccl/codec/lte/include
 /Users/zhangchao/code/b57.6_opt/Code_USF/ccl/data_struct/include
 /Users/zhangchao/code/b57.6_opt/Code_USF/ccl/generic/include
 /Users/zhangchao/code/b57.6_opt/Code_USF/ccl/pool/include
 /Users/zhangchao/code/b57.6_opt/Code_USF/ccl/timer/include
 /Users/zhangchao/code/b57.6_opt/Code_USF/dbs/access/include
 /Users/zhangchao/code/b57.6_opt/Code_USF/dbs/adapter/include
 /Users/zhangchao/code/b57.6_opt/Code_USF/dbs/agent/include
 /Users/zhangchao/code/b57.6_opt/Code_USF/dbs/common/include
 /Users/zhangchao/code/b57.6_opt/Code_USF/dbs/pub/include
 /Users/zhangchao/code/b57.6_opt/Code_USF/dbs/test/include
 /Users/zhangchao/code/b57.6_opt/Code_USF/pub/include
 /Users/zhangchao/code/b57.6_opt/Code_USF/rnlc/common/include
 /Users/zhangchao/code/b57.6_opt/Code_USF/rnlc/pub/include
 /Users/zhangchao/code/b57.6_opt/Code_USF/rnlu/common/include
 /Users/zhangchao/code/b57.6_opt/Code_USF/rnlu/pub/include
 /Users/zhangchao/code/b57.6_opt/Code_USF/rrm/common/include
 /Users/zhangchao/code/b57.6_opt/Code_USF/rrm/pub/include
 /Users/zhangchao/code/b57.6_opt/Code_USF/ssl/pub/include
 /Users/zhangchao/code/b57.6_opt/Code_USF/ssl/ssl/include
 /Users/zhangchao/code/b57.6_opt/Code_LTE/rnlc/cpm/common/include
 /Users/zhangchao/code/b57.6_opt/Code_LTE/rnlc/cpm/cpm_m2ap/include
 /Users/zhangchao/code/b57.6_opt/Code_LTE/rnlc/cpm/cpm_main/include
 /Users/zhangchao/code/b57.6_opt/Code_LTE/rnlc/cpm/cpm_mts/include
 /Users/zhangchao/code/b57.6_opt/Code_LTE/rnlc/cpm/cpm_rim/include
 /Users/zhangchao/code/b57.6_opt/Code_LTE/rnlc/cpm/cpm_s1/include
 /Users/zhangchao/code/b57.6_opt/Code_LTE/rnlc/cpm/cpm_x2/include
 /Users/zhangchao/code/b57.6_opt/Code_LTE/rnlc/cpm/cpm_xc/include
 /Users/zhangchao/code/b57.6_opt/Code_LTE/rnlc/ccm/cim/include
 /Users/zhangchao/code/b57.6_opt/Code_LTE/rnlc/ccm/cmm/include
 /Users/zhangchao/code/b57.6_opt/Code_LTE/rnlc/ccm/common/include
 /Users/zhangchao/code/b57.6_opt/Code_LTE/rnlc/ccm/prm/include
 /Users/zhangchao/code/b57.6_opt/Code_LTE/rnlc/dcm/common/include
 /usr/include/c++
cpp_search_path:
 /Users/zhangchao/code/b57.6_opt/Code_LTE/rnlc/dcm/ng/src
cpp_output_path:
    tmp
include_output_path:
